version: '3.8'

services:
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet

  todo-service:
    build:
      context: ./todo-server
      dockerfile: Dockerfile
    command: npm run start
    ports:
      - "5100:5100"
    depends_on:
      mongodb:
        condition: service_healthy
    environment:
      - SERVICE_NAME=todo-service
      - SERVICE_PORT=5100
      - LOG_LEVEL=info
      - MONGO_URI=mongodb://mongodb:27017/todos
    volumes:
      - ./todo-server:/usr/src/app
      - /usr/src/app/node_modules
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5100/health"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s

  todo-app:
    build:
      context: ./todo-app
      dockerfile: Dockerfile
      args:
        EVIRONMENT: docker-compose
    ports:
      - "3100:3100"
    depends_on:
      mongodb:
        condition: service_healthy
      todo-service:
        condition: service_healthy

volumes:
  mongodb_data: