apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: hometask
configMapGenerator:
- envs:
  - settings.env
  name: todo-service-settings
resources:
  - ../../base
patches:
- path: todo-service.yaml